name: 'CI'
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    name: 'Builds and Compiles'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - run: ./build/setup-emsdk.sh
      - run: echo "/opt/dev/emsdk/upstream/emscripten" >> $GITHUB_PATH
      - run: echo "/opt/dev/emsdk" >> $GITHUB_PATH
      - run: npm ci
      - run: npm run build-onig
      - run: npm run build-wasm
      - run: npm run build-tsc
      - run: npm run package
      - run: npm test

      - name: Setup Github Actions # allow use of `git push`
        run: | # shell
          git config --global user.name "RedCMD"
          git config --global user.email "theredcmd@gmail.com"

      - name: Commit .wasm file # make it public
        run: | #shell
          node ./scripts/cp ./release/onig.wasm ./Onigmo.wasm
          git add Onigmo.wasm
          git diff-index --quiet HEAD || git commit -m "Update Onigmo.wasm"
          git push
