name: 'CI'
on:
  push:
    branches:
      - Onigmo
  pull_request:
    branches:
      - Onigmo
  workflow_dispatch:
jobs:
  build:
    name: 'Builds and Compiles'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Setup Github Actions # allow use of `git push`
        run: | # shell
          git config --global user.name "RedCMD"
          git config --global user.email "theredcmd@gmail.com"
          git reset --hard HEAD
          git submodule init
          git submodule update --init
          git submodule foreach git reset --hard

      - run: ./build/setup-emsdk.sh
      - run: echo "/opt/dev/emsdk/upstream/emscripten" >> $GITHUB_PATH
      - run: echo "/opt/dev/emsdk" >> $GITHUB_PATH
      - run: npm ci
      - run: npm run build-onig
      - run: npm run build-wasm
      - run: npm run build-tsc
      - run: npm run package
      - run: npm test

      - name: Commit release files # make it public
        run: | #shell
          git add .
          git diff-index --quiet HEAD || git commit -am "Update release files"
          git push
