name: 'CI'
on: [push, pull_request]
permissions: {}
jobs:
  build:
    name: 'Builds and Compiles'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: ./build/setup-emsdk.sh
      - run: echo "/opt/dev/emsdk/upstream/emscripten" >> $GITHUB_PATH
      - run: echo "/opt/dev/emsdk" >> $GITHUB_PATH
      - run: npm ci
      - run: npm run build-onig
      - run: npm run build-wasm
      - run: npm run build-tsc
      - run: npm run package
      - run: npm test
